#Plugin need LuckyPerms and WorldEdit with WorldGuardian.
ChatModule: true
RandomTeleport: true
JoinMessage: true
EnableMotd: true
Motd: "Daily message!"
ReloadMessage: "&3[PoL] Plugin reload."
DontHavePermission: "&c[PoL] You don't have a permission."