localChatEnable: true
Chats:
  Trade:
    Symbol: "@"
    Permission: "trade"
    Format: "test"
  Global:
    Symbol: "!"
    Permission: "PoL.Chat.Global"
    Format: "&2[G] &7%PREFIX%PLAYER&f%SUFFIX: %MESSAGE"
#If global is enabled, there working with local chat on range.
#Default range 150.
rangeChat: 150
#%PREFIX %PLAYER %SUFFIX %MESSAGE
ConsoleSenderFormat: "&c[CONSOLE]: &3%MESSAGE"
MessageFormat: "&7%PREFIX%PLAYER&f%SUFFIX: %MESSAGE"
LocalChatFormat: "&9[L] &7%PREFIX%PLAYER&f%SUFFIX: %MESSAGE"
DontHavePermission: "&cYou don't have permission."