localChatEnable: true
Chats:
  Trade:
    Symbol: "@"
    Permission: "PoL.Chat.Trade"
    Format: "&6[T] &7%PREFIX%PLAYER&f%SUFFIX: %MESSAGE"
  Global:
    Symbol: "!"
    Permission: "PoL.Chat.Global"
    Format: "&2[G] &7%PREFIX%PLAYER&f%SUFFIX: %MESSAGE"
#If global is enabled, there working with local chat on range.
#Default range 150.
rangeChat: 150
#%PREFIX %PLAYER %SUFFIX %MESSAGE
#Clear MessageIsEmpty if you want nothing to send.
MessageIsEmpty: "&cYour message is empty!"
ConsoleSenderFormat: "&c[CONSOLE]: &3%MESSAGE"
MessageFormat: "&7%PREFIX%PLAYER&f%SUFFIX: %MESSAGE"
LocalChatFormat: "&9[L] &7%PREFIX%PLAYER&f%SUFFIX: %MESSAGE"
MSGSenderFormat: "&6-> [%PLAYER] %MESSAGE"
MSGMessageFormat: "&6<- [%PLAYER] %MESSAGE"
PlayerIsOffline: "&cPlayer %PLAYER is offline"
DontHavePermission: "&cYou don't have a permission."
